# arguments for dataset
dataset: cdd
nclass: 2
crop_size: 256
data_root: /data/sjh/semi_dataset/CDD/

# arguments for training
epochs: 80
batch_size: 4 # per GPU x 1 GPU
lr: 0.01
lr_multi: 1.0
conf_thresh: 0.95
lr_min: 0.004

# arguments for model
model: deeplabv3plusattn
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
drop_ratio: 0.3
patch_num: [8, 8]
conf_thres: 0.2
